### ISSUE TITLE
Code For Testing

### ISSUE THREAD

**Issue by rupalkapdi** [zsdonghao/u-net-brain-tumor#16]
Thank you for sharing your code. 
I have trained the model and getting the .npz file which contains weights of the trained model.
Can you share the code for testing the images?
Thank you.

**Comment by PoonamZ** [comment]
@rupalkapdi have you saved the volume of predicted tumor results ?
If yes, please can you share the code .

**Comment by rupalkapdi** [comment]
I have used the same code which is provide @ zsdonghao/u-net-brain-tumor

**Comment by PoonamZ** [comment]
ok
thank you .

**Comment by denzilsaldanha** [comment]
How exactly how you used the code for testing purposes?

**Comment by dxs66** [comment]
@rupalkapdi The meaning you said is that when you had run the model.py,you can get the .npz files ？And can you tell me ,after running the model.py where the .npz files is .

**Comment by dxs66** [comment]
@rupalkapdi Can you give me the test.py and the test image? Thank you !

**Comment by rupalkapdi** [comment]
Yes I get the .npz file which contains the weights for the U-net architecture. That file is created in checkpoints folder.

**Comment by rupalkapdi** [comment]
@dxs66 Within a day or two i will upload that file. Thank you.

**Comment by rupalkapdi** [comment]
@dxs66  I will upload this file within some days. 
Thank you.

**Comment by dxs66** [comment]
@rupalkapdi  Hi, runpalkapdi. After I run the train.py, I just get the checkpoint folder. But there are no files in the folder? I just run the cold the same as zsdonghao/u-net-brain-tumor. My turn is that paper_data_with_valid.py , model.py ,train.py .

**Comment by PoonamZ** [comment]
@rupalkapdi can you please share the checkpoints for the necrotic, edema and enhanced.

thank you.

**Comment by PoonamZ** [comment]
ok 
Thank you.

**Comment by TigabuYaya** [comment]
Dear all, can you please share me the outputs u got. Everything u discused here.

**Comment by rupalkapdi** [comment]
@yaoyao14 You have to run train.py file directly. You will get the npz file in checkpoint folder after one successful epoch training. Afterwards same npz file is updated on completion of each epoch.

**Comment by adarsheng1** [comment]
Hi rupalkapdi. How much time does it take to create the npz file for first time.

**Comment by rupalkapdi** [comment]
> Hi rupalkapdi. How much time does it take to create the npz file for first time.

Running this code, on lower capacity GPU for 100 epochs takes around 7 days.

**Comment by cnuzh** [comment]
> Thank you for sharing your code.
> I have trained the model and getting the .npz file which contains weights of the trained model.
> Can you share the code for testing the images?
> Thank you.

Hi,do you have the testing code,now?

**Comment by rupalkapdi** [comment]
Yes, I have developed from training code itself.

**Comment by cnuzh** [comment]
> Yes, I have developed from training code itself.

could you share it with me？Many,thanks.

**Comment by adarsheng1** [comment]
Hi rupalkapdi

I am runnning my code since many days. Only 3 epochs are generated. I don't have GPU and I am using CPU for this code. 
I have 2.7 GHz CPU and 16 GB RAM.
Is it possible with this configuration?

**Comment by rupalkapdi** [comment]
No, It will take too long to complete. We need GPU to run this code. 

Thank you.

**Comment by rupalkapdi** [comment]
> > Yes, I have developed from training code itself.
> 
> could you share it with me？Many,thanks.

Can you share your id on which I send the code?

**Comment by BIGGERYI** [comment]
Hi rupalkapdi, I have trained the medel, could you share the testing code with me?
Thank you.

**Comment by adarsheng1** [comment]
Hi rupalkapdi, What is the minimum GPU configuration required for this code.

**Comment by cnuzh** [comment]
> > > Yes, I have developed from training code itself.
> > 
> > 
> > could you share it with me？Many,thanks.
> 
> Can you share your id on which I send the code?
My email address is hao_zhang12345@163.com.Many thanks!

**Comment by rupalkapdi** [comment]
@adarsheng1 depends on the GPU configuration

**Comment by rupalkapdi** [comment]
@cnuzh Sent

**Comment by cnuzh** [comment]
> @cnuzh Sent

Thanks！

**Comment by GYN199** [comment]
Hello, thank you very much for the code you Shared. Can you share the code for testing the images? Thank you very much.

**Comment by adarsheng1** [comment]
Hi @rupalkapdi Can you please tell what is your GPU configuration. Can you please give me the test.py and the test image?

**Comment by adarsheng1** [comment]
Hi Cnuzh
Can you please share the test.py and test image. My email id is adarsheng1@gmail.com

**Comment by sapnii2** [comment]
> > Hi rupalkapdi. How much time does it take to create the npz file for first time.
> 
> Running this code, on lower capacity GPU for 100 epochs takes around 7 days.

>>>It took 7 hrs to me strange.

**Comment by chaymaalyoubi** [comment]
> @cnuzh Sent

hey can you please send me the code for test too , here is my email , chaymaa.lyo44@gmail.com

**Comment by TigabuYaya** [comment]
can you send me the code for the test? My email address is
tyaya.mit@gmail.com

**Comment by sapnii2** [comment]
There is one bug in code and I am trying to resolve it. I will upload once
resolved.

Thanks & regards,

Swapnakumari
Pune
Cell: 09881083856

**Comment by sapnii2** [comment]
There is one bug in code and I am trying to resolve it. I will upload once
resolved.


Thanks & regards,

Swapnakumari
Pune
Cell: 09881083856

**Comment by bhparmar** [comment]
I am training the model 64 RAM DLGPU system.
can you please send me the testing code. bhparmar@ldce.ac.in

**Comment by conglin10** [comment]
Could you please send me the testing code？Thank you so much！ 327231509@qq.com

**Comment by chaymaalyoubi** [comment]
Hey sorry i still dont have the test code, the owner of the code has told
me that he has a bug in the code

**Comment by cnuzh** [comment]
---Original---

**Comment by Wytres** [comment]
Hi @rupalkapdi~ I‘m training the model these days. Could you please share the test.py and the test image with me. Many thanks~~~And my eamil is 1757422665@qq.com.

**Comment by Anuj-IITBHU** [comment]
> Yes, I have developed from training code itself.

Could you please share it. My email is mail.anuj96@gmail.com

**Comment by TigabuYaya** [comment]
Can you please send me the output of this project. I especially need the
segmented images. my email address is tyaya.mit@gmail.com
